import Link from 'next/link';
import {
  summary, volume, weekly, averageLitres, companies,
} from '@/lib/data';
import {
  FINDINGS, OPPORTUNITIES, OPPORTUNITY_TAKEAWAY, ABOUT_FILLIT, CLOSING_LINE,
  METHOD_NOTE, PAIN_POINTS,
} from '@/lib/content';
import Hero from '@/components/home/Hero';
import VolumePanel from '@/components/home/VolumePanel';
import ForkliftMoment from '@/components/home/ForkliftMoment';
import FunnelBar from '@/components/charts/FunnelBar';
import WeeklyProgress from '@/components/charts/WeeklyProgress';
import { Reveal, SectionHeading, SourceLine, Takeaway, Stagger, StaggerItem } from '@/components/ui/Section';
import { ConfidenceBadge } from '@/components/ui/Badges';
import CountUp from '@/components/ui/CountUp';
import { num, pct } from '@/lib/format';

export default function HomePage() {
  const total = summary.companies;
  const equipment = PAIN_POINTS.find((p) => p.theme === 'Equipment, generator and forklift')!;

  const averages = {
    hot: averageLitres('Hot'),
    warm: averageLitres('Warm'),
    cold: averageLitres('Cold'),
  };

  return (
    <>
      <Hero
        total={total}
        headline={[
          { value: summary.diesel_users, label: 'confirmed diesel users' },
          { value: summary.self_generated, label: 'leads generated by us' },
          { value: summary.cafu_mentions, label: 'companies left a rival' },
        ]}
      />

      {/* ------------------- the market map ------------------- */}
      <section className="shell py-20 md:py-28">
        <Reveal>
          <SectionHeading
            eyebrow="The market we mapped"
            title="568 companies, every one classified."
            standfirst={`${num(summary.field_visits)} field visits resolved to ${num(total)} unique companies. Each is shown at its latest status. Select any band to open its companies.`}
            confidence="VERIFIED"
          />
          <FunnelBar total={total} />

          <div className="mt-12 grid gap-10 border-t border-hairline pt-10 lg:grid-cols-[1fr_1.1fr] lg:gap-16">
            <div>
              <p className="eyebrow">The addressable pool is not 157</p>
              <p className="display mt-6 text-[clamp(3rem,9vw,6rem)] leading-none text-red">
                <CountUp to={summary.blocked_or_unresolved} />
              </p>
              <p className="mt-5 max-w-md text-[1.0625rem] leading-relaxed text-graphite">
                more companies are blocked or unresolved, not rejected. The process stopped; the
                company did not.
              </p>
            </div>

            <dl className="grid grid-cols-2 gap-x-8 gap-y-8 self-center">
              <div>
                <dt className="eyebrow">Confirmed diesel users</dt>
                <dd className="display tnum mt-2.5 text-[2.25rem] leading-none">
                  <CountUp to={summary.diesel_users} />
                </dd>
                <p className="source-line mt-1">{pct((summary.diesel_users / total) * 100, 1)} of the book</p>
              </div>
              <div>
                <dt className="eyebrow">Hot leads asking for a quote</dt>
                <dd className="display tnum mt-2.5 text-[2.25rem] leading-none">
                  <CountUp to={summary.hot} />
                </dd>
              </div>
              <div>
                <dt className="eyebrow">Named fuel decision-makers</dt>
                <dd className="display tnum mt-2.5 text-[2.25rem] leading-none">
                  <CountUp to={summary.decision_makers} />
                </dd>
              </div>
              <div>
                <dt className="eyebrow">Closed on a wrong address</dt>
                <dd className="display tnum mt-2.5 text-[2.25rem] leading-none">
                  <CountUp to={summary.invalid_wrong_address} />
                </dd>
                <p className="source-line mt-1">of {num(summary.invalid)} closed records</p>
              </div>
            </dl>
          </div>

          <SourceLine>
            Source: {`Combined_week1-week5.xlsx and Combined_week6.xlsx, 7 Aug to 17 Sep 2026`} ·
            n = {num(total)} unique companies from {num(summary.field_visits)} field visits · each
            company counted once, at its latest status.
          </SourceLine>
        </Reveal>
      </section>

      {/* ------------------- the headline finding ------------------- */}
      <section className="shell pb-20 md:pb-28">
        <Reveal>
          <VolumePanel volume={volume} averages={averages} />
        </Reveal>
      </section>

      {/* ------------------- the five findings ------------------- */}
      <section className="border-t border-hairline">
        <div className="shell py-16">
          <p className="eyebrow eyebrow-rule">Top five findings</p>
        </div>

        {FINDINGS.map((f, i) => (
          <article key={f.slug} className={`border-t border-hairline ${i % 2 === 1 ? 'bg-white/35' : ''}`}>
            <div className="shell grid gap-8 py-14 lg:grid-cols-[5rem_1fr_auto] lg:gap-12 lg:py-16">
              <p className="display tnum text-[2.5rem] leading-none text-red">{f.n}</p>

              <div>
                <h2 className="display max-w-2xl text-[clamp(1.4rem,2.9vw,2rem)]">{f.title}</h2>
                <p className="mt-5 max-w-2xl text-[1.0625rem] leading-relaxed text-graphite">
                  {f.evidence}
                </p>
                <Link
                  href={f.href}
                  className="mt-6 inline-flex items-center gap-2 text-[0.75rem] font-600 uppercase tracking-[0.1em] text-ink underline decoration-red decoration-2 underline-offset-[6px]"
                >
                  See the evidence <span aria-hidden>→</span>
                </Link>
              </div>

              <div className="lg:w-56 lg:text-right">
                <ConfidenceBadge level={f.confidence} />
                <p className="display tnum mt-5 text-[clamp(2rem,4vw,3rem)] leading-none">{f.stat.value}</p>
                <p className="mt-2.5 text-[0.8125rem] leading-snug text-graphite">{f.stat.caption}</p>
              </div>
            </div>
          </article>
        ))}
      </section>

      {/* ------------------- forklift moment ------------------- */}
      <ForkliftMoment
        companies={equipment.companies}
        hot={equipment.hot}
        warm={equipment.warm}
        cold={equipment.cold}
      />

      {/* ------------------- opportunity map ------------------- */}
      <section className="shell py-20 md:py-28">
        <Reveal>
          <SectionHeading
            eyebrow="Business opportunity map"
            title="Six customer problems, and the opening each one creates."
            standfirst="Each row is a named group of companies in the handover files, not a market segment estimate."
            confidence="VERIFIED"
          />

          <Stagger as="ul" className="grid gap-px border border-hairline bg-hairline md:grid-cols-2">
            {OPPORTUNITIES.map((o) => (
              <StaggerItem as="li" key={o.problem} className="flex gap-6 bg-paper p-7">
                <span className="display tnum shrink-0 text-[2rem] leading-none text-red">
                  {o.companies}
                </span>
                <div>
                  <h3 className="font-display text-[1.0625rem] font-600 leading-snug tracking-display text-ink">
                    {o.problem}
                  </h3>
                  <p className="mt-2.5 text-[0.875rem] leading-relaxed text-graphite">{o.opening}</p>
                </div>
              </StaggerItem>
            ))}
          </Stagger>

          <Takeaway>{OPPORTUNITY_TAKEAWAY}</Takeaway>
        </Reveal>
      </section>

      {/* ------------------- weekly ------------------- */}
      <section className="shell pb-20 md:pb-28">
        <Reveal>
          <SectionHeading
            eyebrow="Weekly progress"
            title="Week 1 taught us to stop working the list."
            standfirst={METHOD_NOTE}
            confidence="VERIFIED"
          />
          <WeeklyProgress weekly={weekly} />
          <Takeaway>
            Weeks 2 to 5, when we generated our own leads, ran at 19% to 30% dead ends. Week 6 was
            mostly revisits and gated sites.
          </Takeaway>
        </Reveal>
      </section>

      {/* ------------------- close ------------------- */}
      <section className="on-ink">
        <div className="shell py-24 text-center md:py-32">
          <p className="display mx-auto max-w-4xl text-[clamp(1.75rem,4.4vw,3rem)]">{CLOSING_LINE}</p>
          <p className="mx-auto mt-8 max-w-2xl text-[0.9375rem] leading-relaxed text-paper/60">
            {ABOUT_FILLIT}
          </p>
          <div className="mt-12 flex flex-wrap justify-center gap-4">
            <Link
              href="/companies"
              className="inline-flex items-center gap-2 bg-red px-5 py-3 text-[0.75rem] font-600 uppercase tracking-[0.1em] text-paper transition-colors hover:bg-[#a81824]"
            >
              Open the database
            </Link>
            <Link
              href="/recommendations"
              className="inline-flex items-center gap-2 border border-paper/30 px-5 py-3 text-[0.75rem] font-600 uppercase tracking-[0.1em] text-paper transition-colors hover:border-paper"
            >
              What we recommend
            </Link>
          </div>
          <p className="mt-10 text-[0.75rem] text-paper/40">
            {num(companies.length)} companies · {num(summary.field_visits)} visits · every figure
            traces to the handed-over workbook.
          </p>
        </div>
      </section>
    </>
  );
}
